force-app/main/default/objects/OmsLog__c/OmsLog__c.object-meta.xml
<CustomObject>
    <description>Custom log for Salesforce Order Management project.</description>
    <label>Oms Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oms Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OmsLog__c/fields/AttachedToId__c.field-meta.xml
<CustomField>
    <fullName>AttachedToId__c</fullName>
    <description>Id of the related/attached.</description>
    <inlineHelpText>Id of the related/attached.</inlineHelpText>
    <label>Attached To</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OmsLog__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the log.</description>
    <inlineHelpText>Category of the log.</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OmsLog__c/fields/IsError__c.field-meta.xml
<CustomField>
    <fullName>IsError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked/true triggers sending log email flow.</description>
    <inlineHelpText>If checked/true triggers sending log email flow.</inlineHelpText>
    <label>Is Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OmsLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Log message.</description>
    <inlineHelpText>Log message.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/utils/LogUtils.cls
/**
* @author Firat Esmer <firat.esmer@osf.digital>
* @date 23/01/2021
* @description Log utils class
*/
public with sharing class LogUtils {
    /**
    * @description Creates Oms log object
    * @param attachedToId Attached/related object Id
    * @param category Category of the log
    * @param message Message of the log
    * @return OmsLog__c instance
    */
    public static OmsLog__c createErrorLog(String attachedToId, String category, String message) {
        OmsLog__c log = new OmsLog__c();
        log.AttachedToId__c = attachedToId;
        log.Category__c = category;
        log.Message__c = message;
        log.IsError__c = true;
        return log;
    }

    /**
    * @description Creates Oms log object
    * @param category Category of the log
    * @param message Message of the log
    * @return OmsLog__c instance
    */
    public static OmsLog__c createErrorLog(String category, String message) {
        OmsLog__c log = new OmsLog__c();
        log.Category__c = category;
        log.Message__c = message;
        log.IsError__c = true;
        return log;
    }

    /**
    * @description Creates Oms log object
    * @param attachedToId Attached/related object Id
    * @param category Category of the log
    * @param message Message of the log
    * @return OmsLog__c instance
    */
    public static OmsLog__c createInfoLog(String attachedToId, String category, String message) {
        OmsLog__c log = new OmsLog__c();
        log.AttachedToId__c = attachedToId;
        log.Category__c = category;
        log.Message__c = message;
        return log;
    }

    /**
    * @description Creates Oms log object
    * @param category Category of the log
    * @param message Message of the log
    * @return OmsLog__c instance
    */
    public static OmsLog__c createInfoLog(String category, String message) {
        OmsLog__c log = new OmsLog__c();
        log.Category__c = category;
        log.Message__c = message;
        return log;
    }
}