force-app/main/default/objects/OmsLog__c/OmsLog__c.object-meta.xml
<CustomObject>
    <description>Custom log for Salesforce Order Management project.</description>
    <label>Oms Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oms Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OmsLog__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the log.</description>
    <inlineHelpText>Category of the log.</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/connectApi/ConnectApiOmnichannelInventoryBaseTest.cls
/**
* @author Firat Esmer <firat.esmer@osf.digital>
* @date 24/07/2021
* @description ConnectApiOmnichannelInventoryBase test class
*/
@isTest
private class ConnectApiOmnichannelInventoryBaseTest {
    /**
    * @description Test method of 
    *   ConnectApiOmnichannelInventoryBase.insertFailedResults
    */
    @isTest
    static void shouldInsertFailedResultsForBaseOutput() {
        ConnectApi.OCIGetInventoryAvailabilityOutputRepresentation output = OmnichannelInventoryTestDataFactory.getFailInventoryAvailabilityOutputRepresentation();

        Test.startTest();
        new OmnichannelInventoryServiceApi().insertFailedResults(output);
        Test.stopTest();

        // Log with category 001 is created in OmnichannelInventoryTestDataFactory
        List<OmsLog__c> logs = [SELECT Id FROM OmsLog__c WHERE Category__c = '001'];

        System.assert(!logs.isEmpty(), 'No log records found');
    }

    /**
    * @description Test method of 
    *   ConnectApiOmnichannelInventoryBase.insertFailedResults
    */
    @isTest
    static void shouldInsertFailedResultsForCreateReservationOutput() {
        ConnectApi.OCICreateReservationOutputRepresentation output = OmnichannelInventoryTestDataFactory.getFailCreateReservationOutput();

        Test.startTest();
        new OmnichannelInventoryServiceApi().insertFailedResults(output);
        Test.stopTest();

        // Log with category 001 is created in OmnichannelInventoryTestDataFactory
        List<OmsLog__c> logs = [SELECT Id FROM OmsLog__c WHERE Category__c = '001'];

        System.assert(!logs.isEmpty(), 'No log records found');
    }

    /**
    * @description Test method of 
    *   ConnectApiOmnichannelInventoryBase.insertFailedResults
    */
    @isTest
    static void shouldInsertFailedResultsForFulfillReservationOutput() {
        ConnectApi.OCIFulfillReservationOutputRepresentation output = OmnichannelInventoryTestDataFactory.getFailFulfillReservationOutput();

        Test.startTest();
        new OmnichannelInventoryServiceApi().insertFailedResults(output);
        Test.stopTest();

        // Log with category 001 is created in OmnichannelInventoryTestDataFactory
        List<OmsLog__c> logs = [SELECT Id FROM OmsLog__c WHERE Category__c = '001'];

        System.assert(!logs.isEmpty(), 'No log records found');
    }

    /**
    * @description Test method of 
    *   ConnectApiOmnichannelInventoryBase.insertFailedResults
    */
    @isTest
    static void shouldInsertFailedResultsForReleaseReservationOutput() {
        ConnectApi.OCIReleaseReservationOutputRepresentation output = OmnichannelInventoryTestDataFactory.getFailReleaseReservationOutput();

        Test.startTest();
        new OmnichannelInventoryServiceApi().insertFailedResults(output);
        Test.stopTest();

        // Log with category 001 is created in OmnichannelInventoryTestDataFactory
        List<OmsLog__c> logs = [SELECT Id FROM OmsLog__c WHERE Category__c = '001'];

        System.assert(!logs.isEmpty(), 'No log records found');
    }

    /**
    * @description Test method of 
    *   ConnectApiOmnichannelInventoryBase.insertFailedResults
    */
    @isTest
    static void shouldInsertFailedResultsForFailTransferReservationOutput() {
        ConnectApi.OCITransferReservationOutputRepresentation output = OmnichannelInventoryTestDataFactory.getFailTransferReservationOutput();

        Test.startTest();
        new OmnichannelInventoryServiceApi().insertFailedResults(output);
        Test.stopTest();

        // Log with category 001 is created in OmnichannelInventoryTestDataFactory
        List<OmsLog__c> logs = [SELECT Id FROM OmsLog__c WHERE Category__c = '001'];

        System.assert(!logs.isEmpty(), 'No log records found');
    }
}