force-app/main/default/objects/OmsLog__c/OmsLog__c.object-meta.xml
<CustomObject>
    <description>Custom log for Salesforce Order Management project.</description>
    <label>Oms Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oms Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OmsLog__c/fields/AttachedToId__c.field-meta.xml
<CustomField>
    <fullName>AttachedToId__c</fullName>
    <description>Id of the related/attached.</description>
    <inlineHelpText>Id of the related/attached.</inlineHelpText>
    <label>Attached To</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OmsLog__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the log.</description>
    <inlineHelpText>Category of the log.</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OmsLog__c/fields/IsError__c.field-meta.xml
<CustomField>
    <fullName>IsError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked/true triggers sending log email flow.</description>
    <inlineHelpText>If checked/true triggers sending log email flow.</inlineHelpText>
    <label>Is Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OmsLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Log message.</description>
    <inlineHelpText>Log message.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/utils/LogUtilsTest.cls
/**
* @author Firat Esmer <firat.esmer@osf.digital>
* @date 23/01/2021
* @description Log utils test class
*/
@isTest
private class LogUtilsTest {
    /**
    * @description Test method of LogUtils.createErrorLog
    */
    @isTest
    static void shouldLogErrorWithAttachId() {
        String lastName = 'Doe';
        String category = 'Unit Test';
        String message = 'Unit test error';

        Contact contactToInsert = new Contact(Lastname=lastName);
        insert contactToInsert;

        String attachId = contactToInsert.Id;

        System.Test.startTest();
        OmsLog__c logToInsert = LogUtils.createErrorLog(attachId, category, message);
        insert logToInsert;
        System.Test.stopTest();

        OmsLog__c log = [SELECT AttachedToId__c, Category__c, Message__c, IsError__c FROM OmsLog__c WHERE Id =: logToInsert.Id];

        System.assert(log.AttachedToId__c.equals(attachId), 'Attached to Id doesn\'t match');
        System.assert(log.Category__c.equalsIgnoreCase(category), 'Category of the log doesn\'t match');
        System.assert(log.Message__c.equalsIgnoreCase(message), 'Message of the log doesn\'t match');
        System.assert(log.IsError__c, 'IsError should be checked/true');
    }

    /**
    * @description Test method of LogUtils.createErrorLog
    */
    @isTest
    static void shouldLogError() {
        String category = 'Unit Test';
        String message = 'Unit test error';

        System.Test.startTest();
        OmsLog__c logToInsert = LogUtils.createErrorLog(category, message);
        insert logToInsert;
        System.Test.stopTest();

        OmsLog__c log = [SELECT AttachedToId__c, Category__c, Message__c, IsError__c FROM OmsLog__c WHERE Id =: logToInsert.Id];

        System.assert(log.Category__c.equalsIgnoreCase(category), 'Category of the log doesn\'t match');
        System.assert(log.Message__c.equalsIgnoreCase(message), 'Message of the log doesn\'t match');
        System.assert(log.IsError__c, 'IsError should be checked/true');
    }

    /**
    * @description Test method of LogUtils.createInfoLog
    */
    @isTest
    static void shouldLogInfoWithAttachId() {
        String lastName = 'Doe';
        String category = 'Unit Test';
        String message = 'Unit test error';

        Contact contactToInsert = new Contact(Lastname=lastName);
        insert contactToInsert;

        String attachId = contactToInsert.Id;

        System.Test.startTest();
        OmsLog__c logToInsert = LogUtils.createInfoLog(attachId, category, message);
        insert logToInsert;
        System.Test.stopTest();

        OmsLog__c log = [SELECT AttachedToId__c, Category__c, Message__c, IsError__c FROM OmsLog__c WHERE Id =: logToInsert.Id];

        System.assert(log.AttachedToId__c.equals(attachId), 'Attached to Id doesn\'t match');
        System.assert(log.Category__c.equalsIgnoreCase(category), 'Category of the log doesn\'t match');
        System.assert(log.Message__c.equalsIgnoreCase(message), 'Message of the log doesn\'t match');
        System.assert(!log.IsError__c, 'IsError should be unchecked/false');
    }

    /**
    * @description Test method of LogUtils.createInfoLog
    */
    @isTest
    static void shouldLogInfo() {
        String category = 'Unit Test';
        String message = 'Unit test error';

        System.Test.startTest();
        OmsLog__c logToInsert = LogUtils.createInfoLog(category, message);
        insert logToInsert;
        System.Test.stopTest();

        OmsLog__c log = [SELECT AttachedToId__c, Category__c, Message__c, IsError__c FROM OmsLog__c WHERE Id =: logToInsert.Id];

        System.assert(log.Category__c.equalsIgnoreCase(category), 'Category of the log doesn\'t match');
        System.assert(log.Message__c.equalsIgnoreCase(message), 'Message of the log doesn\'t match');
        System.assert(!log.IsError__c, 'IsError should be unchecked/false');
    }
}